###Run this after pipelineMaksimovic 
###We need the beta values

##Separate probes by type and print density plots

###Desired columns
#Relation_to_Island
#UCSC_RefGene_Group

#Input: beta-values generated by minfi with getBeta()
bVals <- getBeta(mSetSqFlt)

#Subset annotation to output just two columns
ann450k_passQC<- ann450k[row.names(ann450k) %in% row.names(bVals), c("Relation_to_Island","UCSC_RefGene_Group")]
ann450k_passQC["cpg_ID"]<-row.names(ann450k_passQC)


#Filter islands by different criteria (split annotation by groups)
by_islands<-as.list(split( ann450k_passQC , f = ann450k_passQC$Relation_to_Island ))
by_refGene<-as.list(split( ann450k_passQC , f = ann450k_passQC$UCSC_RefGene_Group ))

head(by_refGene)

outFile<-paste(resultsDirectory,"ALL_densities_byRelation_to_Island.pdf")
#List of data.frames with methylation values separated by island type

pdf(paste0(outFile))
for(i in by_islands){
  filteredVals<-list(length(by_islands))
  typeName<-unique(i$Relation_to_Island)
  
  filteredVals[[typeName]]<- bVals[row.names(bVals) %in% row.names(i), ]
  island<-filteredVals[[typeName]]
  
  write.table(island, paste0(resultsDirectory,typeName,".csv"))
  head(island)
  
  ##Change this with tidyverse tools, like gather()
  
  #####Generate a new table to plot######
  tabla<-matrix(nrow=nrow(island)*ncol(island),ncol=2)
  colnames(tabla)<-c("Bvalues","samples" )
  tabla<-as.data.frame(tabla)
  
  
  tabla[,1]<-island[,1]
  tabla[1:nrow(island),2]<-"a"
  
  tabla[nrow(island)+1:(2*nrow(island)),1]<-island[,2]
  tabla[nrow(island)+1:(2*nrow(island)),2]<-"b"
  
  tabla[(2*nrow(island)+1):(3*nrow(island)),1]<-island[,3]
  tabla[(2*nrow(island)+1):(3*nrow(island)),2]<-"c"
  
  tabla[(3*nrow(island)+1):(4*nrow(island)),1]<-island[,4]
  tabla[(3*nrow(island)+1):(4*nrow(island)),2]<-"d"
  
  res<-ggplot(tabla, aes(x = Bvalues, fill = samples)) + geom_density(alpha = 0.5) + ggtitle(typeName, subtitle = NULL) + ylim(0,10)
  print(res)
  
  
}
dev.off()

#########################################################################


####We need to colapse the refgene classification into broader categories
by_islands<-by_refGene
#outFile<-paste(resultsDirectory,"ALL_densities_byUCSC_RefGene_Group.pdf")
for(i in by_islands){
  typeName<-unique(i$UCSC_RefGene_Group)
  if (typeName == ""){
    next
  }
  filteredVals<-list(length(by_islands))
  
  
  filteredVals[[typeName]]<- bVals[row.names(bVals) %in% row.names(i), ]
  island<-filteredVals[[typeName]]
  
  write.table(island, paste0(resultsDirectory,typeName,".csv"))
  head(island)
}
  

